/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch deployed version metadata */
    get: operations["getVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/portal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch public portal data */
    get: operations["getPortal"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/roadmap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch public roadmap items */
    get: operations["getRoadmap"];
    put?: never;
    /** Create or update a roadmap item */
    post: operations["upsertRoadmapItem"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/changelog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch public changelog entries */
    get: operations["getChangelog"];
    put?: never;
    /** Create or update a changelog entry */
    post: operations["upsertChangelogEntry"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/updates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch user-specific updates */
    get: operations["getUpdates"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch workspace settings */
    get: operations["getWorkspaceSettings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/decisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch automation decisions */
    get: operations["getAutomationDecisions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/build-briefs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch agent-readable build briefs */
    get: operations["getBuildBriefs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/agent-runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch proactive agent run history */
    get: operations["getAgentRuns"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/deliveries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch delivery outbox records */
    get: operations["getDeliveryOutbox"];
    put?: never;
    /** Plan or send delivery records */
    post: operations["planOrSendDeliveries"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/github-app": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch GitHub App install readiness */
    get: operations["getGitHubAppInstallInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workspace projects */
    get: operations["listProjects"];
    put?: never;
    /** Create a workspace project */
    post: operations["createProject"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/plans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch plan catalog */
    get: operations["getPlanCatalog"];
    put?: never;
    /** Update workspace plan */
    post: operations["updatePlan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/_/domains": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resolve a custom domain */
    get: operations["resolveCustomDomain"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/identity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Identify a customer user */
    post: operations["identifyUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create customer feedback */
    post: operations["createFeedback"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/interactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Record a feedback interaction */
    post: operations["recordFeedbackInteraction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Track a product-loop event */
    post: operations["trackEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/github": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ingest a GitHub webhook */
    post: operations["ingestGitHubWebhook"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/source-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch imported source events */
    get: operations["getSourceEvents"];
    put?: never;
    /** Import a source event */
    post: operations["importSourceEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/stripe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ingest a Stripe webhook */
    post: operations["ingestStripeWebhook"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/drafts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Draft changelog copy */
    post: operations["draftChangelog"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Update automation rules */
    post: operations["updateAutomationRules"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upsert a workspace member */
    post: operations["upsertWorkspaceMember"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/integrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upsert an integration connection */
    post: operations["upsertIntegration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/portal-settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Update portal settings */
    post: operations["updatePortalSettings"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/repositories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Connect a GitHub repository */
    post: operations["connectRepository"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/checkout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a checkout session */
    post: operations["createCheckoutSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/preferences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Set notification preferences */
    post: operations["setNotificationPreference"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{workspaceSlug}/domains": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register or verify a custom domain */
    post: operations["registerOrVerifyCustomDomain"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Any JSON-serializable metadata value. */
    JsonValue: unknown;
    JsonObject: {
      [key: string]: unknown;
    };
    ErrorResponse: {
      error: string;
    };
    VersionInfo: {
      /** @description Stable REST API version served by this deployment. */
      apiVersion: string;
      /** @description Build timestamp when provided by AMEND_BUILD_TIME. */
      buildTime?: string;
      /** @description Commit SHA or deployment revision when provided by AMEND_COMMIT_SHA or AMEND_BUILD_SHA. */
      commit?: string;
      /** @enum {string} */
      name: "amend";
      /** @enum {string} */
      source: "backend";
      updateCheck: {
        enabled: boolean;
        privacy: string;
        /** @description Public release metadata URL used by explicit CLI update checks. */
        releaseUrl: string;
      };
      /** @description True when AMEND_DISABLE_VERSION_CHECK=1 is set for the deployment. */
      updateCheckDisabled: boolean;
      /** @description Release tag or application version from AMEND_VERSION. */
      version: string;
    };
    /** @enum {string} */
    RoadmapStatus:
      | "considering"
      | "under_review"
      | "planned"
      | "in_progress"
      | "shipped"
      | "closed"
      | "paused";
    /** @enum {string} */
    RoadmapPriority: "P0" | "P1" | "P2" | "P3";
    /** @enum {string} */
    BuildBriefStatus: "draft" | "in_review" | "approved" | "exported" | "archived";
    /** @enum {string} */
    AgentRunStatus: "completed" | "completed_with_fallback" | "failed";
    /** @enum {string} */
    SourceProvider:
      | "api"
      | "cli"
      | "discord"
      | "email"
      | "embed"
      | "github"
      | "import"
      | "linear"
      | "manual"
      | "portal"
      | "sdk"
      | "slack"
      | "support"
      | "x";
    /** @enum {string} */
    SourceKind:
      | "pull_request"
      | "issue"
      | "release"
      | "label"
      | "milestone"
      | "discussion"
      | "customer_signal"
      | "import_record"
      | "portal_feedback"
      | "support_ticket"
      | "usage_event";
    /** @enum {string} */
    SourceState: "open" | "closed" | "merged" | "published" | "draft";
    /** @enum {string} */
    ChangelogStatus: "draft" | "in_review" | "scheduled" | "published" | "archived";
    /** @enum {string} */
    ChangelogCategory: "added" | "changed" | "fixed" | "removed" | "security";
    /** @enum {string} */
    PlanTier: "free" | "starter" | "pro" | "team" | "scale" | "enterprise" | "open_source";
    /** @enum {string} */
    DeliveryChannel: "email" | "in_app" | "slack" | "webhook";
    /** @enum {string} */
    DomainPurpose: "api" | "embed" | "portal";
    PortalResponse: {
      workspace?: components["schemas"]["Workspace"];
      roadmap?: components["schemas"]["RoadmapItem"][];
      changelog?: components["schemas"]["ChangelogEntry"][];
      feedback?: components["schemas"]["Feedback"][];
    } & {
      [key: string]: unknown;
    };
    UpdatesResponse: {
      changelog: components["schemas"]["ChangelogEntry"][];
      notifications: components["schemas"]["Notification"][];
      roadmap: components["schemas"]["RoadmapItem"][];
      seenUpdateKeys: string[];
      user?: null | components["schemas"]["ExternalUser"];
    };
    Workspace: {
      slug?: string;
      name?: string;
      /** @enum {string} */
      visibility?: "private" | "public";
    } & {
      [key: string]: unknown;
    };
    WorkspaceSettings: {
      workspace?: components["schemas"]["Workspace"];
      members?: components["schemas"]["JsonObject"][];
      integrations?: components["schemas"]["JsonObject"][];
      customDomains?: components["schemas"]["JsonObject"][];
    } & {
      [key: string]: unknown;
    };
    Project: {
      stableKey?: string;
      name?: string;
      slug?: string;
      /** @enum {string} */
      visibility?: "private" | "public";
    } & {
      [key: string]: unknown;
    };
    ProjectInput: {
      description?: string;
      name: string;
      slug?: string;
      /** @enum {string} */
      visibility?: "private" | "public";
    };
    RepositoryInput: {
      defaultBranch?: string;
      owner: string;
      projectKey: string;
      repo: string;
      /** Format: uri */
      repositoryUrl?: string;
    };
    RoadmapItem: {
      stableKey?: string;
      title?: string;
      description?: string;
      status?: components["schemas"]["RoadmapStatus"];
      priority?: components["schemas"]["RoadmapPriority"];
      sourceLinks?: components["schemas"]["SourceLink"][];
    } & {
      [key: string]: unknown;
    };
    RoadmapItemInput: {
      description: string;
      impact?: string;
      priority?: components["schemas"]["RoadmapPriority"];
      stableKey?: string;
      status?: components["schemas"]["RoadmapStatus"];
      target?: string;
      title: string;
    };
    AgentRun: {
      recordId?: string;
      stableKey?: string;
      status?: components["schemas"]["AgentRunStatus"];
      provider?: string;
      providerConfigured?: boolean;
      decisionCount?: number;
      reviewCount?: number;
      sourceEventCount?: number;
      error?: string;
      decisionIds?: string[];
      reviewItemIds?: string[];
      sourceLinks?: components["schemas"]["SourceLink"][];
      startedAt?: number;
      completedAt?: number;
      createdAt?: number;
      updatedAt?: number;
    } & {
      [key: string]: unknown;
    };
    BuildBrief: {
      recordId?: string;
      projectId?: string;
      stableKey?: string;
      title?: string;
      problem?: string;
      evidenceSummary?: string;
      recommendedScope?: string;
      acceptanceCriteria?: string[];
      suggestedFiles?: string[];
      sourceLinks?: components["schemas"]["SourceLink"][];
      feedbackItemIds?: string[];
      roadmapItemIds?: string[];
      changelogEntryIds?: string[];
      sourceEventIds?: string[];
      status?: components["schemas"]["BuildBriefStatus"];
      priority?: components["schemas"]["RoadmapPriority"];
      createdBy?: string;
      createdAt?: number;
      updatedAt?: number;
      exportedAt?: number;
    } & {
      [key: string]: unknown;
    };
    ChangelogEntry: {
      stableKey?: string;
      title?: string;
      summary?: string;
      body?: string;
      status?: components["schemas"]["ChangelogStatus"];
      sourceLinks?: components["schemas"]["SourceLink"][];
    } & {
      [key: string]: unknown;
    };
    ChangelogEntryInput: {
      body: string;
      category?: components["schemas"]["ChangelogCategory"];
      publishedAt?: number;
      scheduledFor?: number;
      stableKey?: string;
      status?: components["schemas"]["ChangelogStatus"];
      summary: string;
      tags?: string[];
      title: string;
      version?: string;
    };
    ChangelogDraftInput: {
      body?: string;
      dryRun?: boolean;
      kind?: string;
      sourceLinks?: components["schemas"]["JsonValue"][];
      title: string;
    };
    ChangelogDraft: {
      body?: string;
      model?: string;
      provider?: string;
      summary?: string;
      title?: string;
    } & {
      [key: string]: unknown;
    };
    FeedbackInput: {
      /** Format: email */
      authorEmail?: string;
      authorName?: string;
      body: string;
      labels?: string[];
      /** Format: uri */
      sourceUrl?: string;
      title: string;
    };
    Feedback: {
      stableKey?: string;
      title?: string;
      body?: string;
      status?: string;
    } & {
      [key: string]: unknown;
    };
    FeedbackInteractionInput: {
      body?: string;
      /** Format: email */
      email?: string;
      externalUserId?: string;
      feedbackKey?: string;
      /** @enum {string} */
      kind: "vote" | "comment" | "reaction";
      reaction?: string;
      requestKey?: string;
      updateKey?: string;
      userId?: string;
    };
    IdentityInput: {
      accountId?: string;
      /** Format: email */
      email?: string;
      externalUserId: string;
      name?: string;
      traits?: components["schemas"]["JsonObject"];
    };
    /** @enum {string} */
    EventName:
      | "identify"
      | "account_identify"
      | "sign_in_failed"
      | "sign_in_submitted"
      | "sign_up_failed"
      | "sign_up_submitted"
      | "user_signed_in"
      | "user_signed_out"
      | "user_signed_up"
      | "agent_run_completed"
      | "changelog_upserted"
      | "feedback_submitted"
      | "project_created"
      | "project_source_connected"
      | "vote_added"
      | "vote_removed"
      | "comment_added"
      | "delivery_planned"
      | "delivery_status_updated"
      | "reaction_added"
      | "review_status_updated"
      | "roadmap_upserted"
      | "roadmap_vote_added"
      | "roadmap_vote_removed"
      | "roadmap_viewed"
      | "changelog_viewed"
      | "source_event_ingested"
      | "update_seen"
      | "shipped_feature_used";
    EventInput: {
      accountId?: string;
      event: components["schemas"]["EventName"];
      externalUserId?: string;
      metadata?: components["schemas"]["JsonObject"];
      updateKey?: string;
      userId?: string;
    };
    NotificationPreferenceInput: {
      accountId?: string;
      digestDay?: string;
      digestHour?: number;
      /** Format: email */
      email?: string;
      externalUserId?: string;
      /** @enum {string} */
      mode: "digest" | "instant" | "muted";
      unsubscribed?: boolean;
      userId?: string;
    };
    AutomationRulesInput: {
      autoDraftChangelog?: boolean;
      autoNotifyUsers?: boolean;
      autoPublishChangelog?: boolean;
      autoUpdateFeedbackStatus?: boolean;
      autoUpdateRoadmapStatus?: boolean;
      byokConfigured?: boolean;
      byokProvider?: string;
      /** @enum {string} */
      mode?: "manual" | "mostly_auto" | "review_first";
      requireReviewBelowConfidence?: number;
      requireReviewForHighImpact?: boolean;
      requireReviewForPublicCopy?: boolean;
    };
    WorkspaceMemberInput: {
      /** Format: email */
      email: string;
      externalUserId?: string;
      name?: string;
      permissions?: string[];
      /** @enum {string} */
      role: "owner" | "admin" | "reviewer" | "member" | "viewer";
      userId?: string;
    };
    IntegrationInput: {
      config?: components["schemas"]["JsonObject"];
      /** @enum {string} */
      direction: "bidirectional" | "inbound" | "outbound";
      displayName?: string;
      /** @enum {string} */
      provider:
        | "databuddy"
        | "discord"
        | "github"
        | "linear"
        | "posthog"
        | "slack"
        | "support"
        | "x";
      /** @enum {string} */
      state: "attention" | "connected" | "disabled" | "planned";
    };
    PortalSettingsInput: {
      accentColor?: string;
      /** @enum {string} */
      changelogVisibility?: "private" | "public";
      /** @enum {string} */
      feedbackMode?: "authenticated" | "closed" | "open";
      headline?: string;
      intro?: string;
      /** @enum {string} */
      roadmapVisibility?: "private" | "public";
    };
    PlanCatalog: {
      [key: string]: unknown;
    };
    PlanUpdateInput: {
      seats?: number;
      tier: components["schemas"]["PlanTier"];
    };
    CheckoutInput: {
      /** Format: uri */
      cancelUrl?: string;
      /** Format: email */
      customerEmail?: string;
      dryRun?: boolean;
      seats?: number;
      /** Format: uri */
      successUrl?: string;
      /** @enum {string} */
      tier: "starter" | "pro" | "team" | "scale";
    };
    CheckoutSession: {
      /** Format: uri */
      checkoutUrl?: string;
      provider?: string;
    } & {
      [key: string]: unknown;
    };
    DeliveryPlanInput: {
      channel?: components["schemas"]["DeliveryChannel"];
      notificationKey?: string;
      provider?: string;
    };
    DeliverySendInput: {
      /** @enum {string} */
      action?: "send";
      channel?: components["schemas"]["DeliveryChannel"];
      dryRun?: boolean;
      limit?: number;
    };
    DeliverySendResult: {
      dryRun?: boolean;
      results?: components["schemas"]["JsonObject"][];
      sent?: number;
    } & {
      [key: string]: unknown;
    };
    Delivery: {
      stableKey?: string;
      channel?: components["schemas"]["DeliveryChannel"];
      recipient?: string;
      status?: string;
    } & {
      [key: string]: unknown;
    };
    DomainRegistrationInput: {
      domain: string;
      purpose?: components["schemas"]["DomainPurpose"];
    };
    DomainVerificationInput: {
      /** @enum {string} */
      action: "verify";
      domain: string;
    };
    DomainResolution: {
      domain?: string;
      purpose?: components["schemas"]["DomainPurpose"];
      resolved?: boolean;
      workspace?: components["schemas"]["Workspace"];
    } & {
      [key: string]: unknown;
    };
    GitHubAppInfo: {
      appId?: string;
      clientId?: string;
      configured: boolean;
      /** Format: uri */
      installUrl?: string;
      missing: string[];
      workspaceSlug: string;
    };
    GitHubWebhookPayload: {
      action?: string;
      event?: string;
      repository?: components["schemas"]["JsonObject"];
      sender?: components["schemas"]["JsonObject"];
    } & {
      [key: string]: unknown;
    };
    SourceLink: {
      provider?: components["schemas"]["SourceProvider"];
      kind?: components["schemas"]["SourceKind"];
      externalId?: string;
      title?: string;
      /** Format: uri */
      url?: string;
    } & {
      [key: string]: unknown;
    };
    SourceEvent: {
      recordId?: string;
      externalId?: string;
      kind?: components["schemas"]["SourceKind"];
      provider?: components["schemas"]["SourceProvider"];
      state?: components["schemas"]["SourceState"];
      title?: string;
      /** Format: uri */
      url?: string;
      labels?: string[];
      observedAt?: number;
    } & {
      [key: string]: unknown;
    };
    SourceEventInput: {
      author?: string;
      /** @description Stable idempotency key from the source system. */
      externalId: string;
      kind: components["schemas"]["SourceKind"];
      labels?: string[];
      milestone?: string;
      number?: number;
      observedAt?: number | string;
      owner?: string;
      projectSlug?: string;
      provider?: components["schemas"]["SourceProvider"];
      repo?: string;
      sourceCreatedAt?: number | string;
      sourceUpdatedAt?: number | string;
      state?: components["schemas"]["SourceState"];
      title: string;
      /** Format: uri */
      url?: string;
    };
    SourceEventImportResult: {
      changelogEntryId?: string;
      notificationId?: string;
      reviewItemId?: string;
      sourceEventId?: string;
      /** @enum {string} */
      status?: "created" | "updated";
    } & {
      [key: string]: unknown;
    };
    AutomationDecision: {
      action?: string;
      confidence?: number;
      rationale?: string;
      sourceEventExternalIds?: string[];
      targetKey?: string;
    } & {
      [key: string]: unknown;
    };
    Notification: {
      stableKey?: string;
      title?: string;
      body?: string;
    } & {
      [key: string]: unknown;
    };
    ExternalUser: {
      externalUserId?: string;
      /** Format: email */
      email?: string;
    } & {
      [key: string]: unknown;
    };
  };
  responses: {
    /** @description Bad request, missing resource, invalid input, or another client-side failure. */
    ClientError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Missing or invalid Amend API token or webhook signature. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    /** @description Public Amend workspace slug. */
    WorkspaceSlug: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getVersion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Version metadata for the running Amend deployment. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionInfo"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  getPortal: {
    parameters: {
      query?: {
        roadmapStatus?: components["schemas"]["RoadmapStatus"];
      };
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Public portal data. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortalResponse"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  getRoadmap: {
    parameters: {
      query?: {
        status?: components["schemas"]["RoadmapStatus"];
      };
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Roadmap items and a tracked roadmap view event. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            roadmap: components["schemas"]["RoadmapItem"][];
          };
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  upsertRoadmapItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoadmapItemInput"];
      };
    };
    responses: {
      /** @description Created or updated roadmap item. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoadmapItem"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getChangelog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Changelog entries and a tracked changelog view event. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            changelog: components["schemas"]["ChangelogEntry"][];
          };
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  upsertChangelogEntry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangelogEntryInput"];
      };
    };
    responses: {
      /** @description Created or updated changelog entry. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChangelogEntry"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getUpdates: {
    parameters: {
      query?: {
        externalUserId?: string;
        /** @deprecated */
        userId?: string;
        email?: string;
      };
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User-filtered notifications plus public roadmap and changelog context. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UpdatesResponse"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  getWorkspaceSettings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace settings for owner/admin surfaces. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceSettings"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  getAutomationDecisions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Source-linked proactive agent decisions. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            decisions: components["schemas"]["AutomationDecision"][];
          };
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  getBuildBriefs: {
    parameters: {
      query?: {
        status?: components["schemas"]["BuildBriefStatus"];
        projectSlug?: string;
      };
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agent-readable build briefs for customer-demand driven implementation. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            buildBriefs: components["schemas"]["BuildBrief"][];
          };
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  getAgentRuns: {
    parameters: {
      query?: {
        projectSlug?: string;
      };
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Persisted proactive agent runs for audit and coding-agent context. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            runs: components["schemas"]["AgentRun"][];
          };
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  getDeliveryOutbox: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Planned delivery outbox records. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            deliveries: components["schemas"]["Delivery"][];
          };
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  planOrSendDeliveries: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json":
          | components["schemas"]["DeliveryPlanInput"]
          | components["schemas"]["DeliverySendInput"];
      };
    };
    responses: {
      /** @description Delivery send result when action is send. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeliverySendResult"];
        };
      };
      /** @description Planned delivery records. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getGitHubAppInstallInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description GitHub App installation readiness. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GitHubAppInfo"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  listProjects: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace projects. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            projects: components["schemas"]["Project"][];
          };
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectInput"];
      };
    };
    responses: {
      /** @description Created project. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getPlanCatalog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Plan catalog and current workspace plan. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanCatalog"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  updatePlan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlanUpdateInput"];
      };
    };
    responses: {
      /** @description Updated plan. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
      "4XX": components["responses"]["ClientError"];
    };
  };
  resolveCustomDomain: {
    parameters: {
      query: {
        domain: string;
        purpose?: components["schemas"]["DomainPurpose"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Domain resolution result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DomainResolution"];
        };
      };
      /** @description Domain was not resolved. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DomainResolution"];
        };
      };
    };
  };
  identifyUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | {
              identity: components["schemas"]["IdentityInput"];
            }
          | components["schemas"]["IdentityInput"];
      };
    };
    responses: {
      /** @description Mapped identity. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  createFeedback: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeedbackInput"];
      };
    };
    responses: {
      /** @description Created feedback request. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Feedback"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  recordFeedbackInteraction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeedbackInteractionInput"];
      };
    };
    responses: {
      /** @description Recorded vote, comment, or reaction. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  trackEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventInput"];
      };
    };
    responses: {
      /** @description Tracked event. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  ingestGitHubWebhook: {
    parameters: {
      query?: never;
      header?: {
        "X-GitHub-Event"?: string;
        "X-GitHub-Delivery"?: string;
        "X-Hub-Signature-256"?: string;
      };
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GitHubWebhookPayload"];
      };
    };
    responses: {
      /** @description Ingested source event. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceEvent"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getSourceEvents: {
    parameters: {
      query?: {
        projectSlug?: string;
        provider?: components["schemas"]["SourceProvider"];
        kind?: components["schemas"]["SourceKind"];
        limit?: number;
      };
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Source evidence imported from GitHub, SDK/API, CLI, portal, and channel adapters. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            sourceEvents: components["schemas"]["SourceEvent"][];
          };
        };
      };
      "4XX": components["responses"]["ClientError"];
    };
  };
  importSourceEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | components["schemas"]["SourceEventInput"]
          | {
              sourceEvent: components["schemas"]["SourceEventInput"];
            };
      };
    };
    responses: {
      /** @description Imported or updated source evidence for the proactive agent loop. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceEventImportResult"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  ingestStripeWebhook: {
    parameters: {
      query?: never;
      header?: {
        "Stripe-Signature"?: string;
      };
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JsonObject"];
      };
    };
    responses: {
      /** @description Processed Stripe event. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  draftChangelog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangelogDraftInput"];
      };
    };
    responses: {
      /** @description Drafted changelog copy. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChangelogDraft"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  updateAutomationRules: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AutomationRulesInput"];
      };
    };
    responses: {
      /** @description Updated automation rules. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  upsertWorkspaceMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkspaceMemberInput"];
      };
    };
    responses: {
      /** @description Upserted workspace member. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  upsertIntegration: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IntegrationInput"];
      };
    };
    responses: {
      /** @description Upserted integration connection. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  updatePortalSettings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortalSettingsInput"];
      };
    };
    responses: {
      /** @description Updated portal settings. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  connectRepository: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RepositoryInput"];
      };
    };
    responses: {
      /** @description Connected repository. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  createCheckoutSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckoutInput"];
      };
    };
    responses: {
      /** @description Dry-run checkout result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckoutSession"];
        };
      };
      /** @description Created Stripe checkout session. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckoutSession"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  setNotificationPreference: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NotificationPreferenceInput"];
      };
    };
    responses: {
      /** @description Updated notification preference. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  registerOrVerifyCustomDomain: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public Amend workspace slug. */
        workspaceSlug: components["parameters"]["WorkspaceSlug"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | components["schemas"]["DomainRegistrationInput"]
          | components["schemas"]["DomainVerificationInput"];
      };
    };
    responses: {
      /** @description Domain verification result. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      /** @description Registered custom domain. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JsonObject"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
}
