/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as EmbedDemoRouteImport } from './routes/embed-demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalWorkspaceSlugRouteImport } from './routes/portal.$workspaceSlug'
import { Route as DashboardViewRouteImport } from './routes/dashboard.$view'
import { Route as ApiOgIndexRouteImport } from './routes/api/og/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOgPortalSlugRouteImport } from './routes/api/og/portal.$slug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedDemoRoute = EmbedDemoRouteImport.update({
  id: '/embed-demo',
  path: '/embed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalWorkspaceSlugRoute = PortalWorkspaceSlugRouteImport.update({
  id: '/portal/$workspaceSlug',
  path: '/portal/$workspaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardViewRoute = DashboardViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiOgIndexRoute = ApiOgIndexRouteImport.update({
  id: '/api/og/',
  path: '/api/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPortalSlugRoute = ApiOgPortalSlugRouteImport.update({
  id: '/api/og/portal/$slug',
  path: '/api/og/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/embed-demo': typeof EmbedDemoRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$view': typeof DashboardViewRoute
  '/portal/$workspaceSlug': typeof PortalWorkspaceSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/api/og/portal/$slug': typeof ApiOgPortalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/embed-demo': typeof EmbedDemoRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$view': typeof DashboardViewRoute
  '/portal/$workspaceSlug': typeof PortalWorkspaceSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og': typeof ApiOgIndexRoute
  '/api/og/portal/$slug': typeof ApiOgPortalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/embed-demo': typeof EmbedDemoRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$view': typeof DashboardViewRoute
  '/portal/$workspaceSlug': typeof PortalWorkspaceSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/api/og/portal/$slug': typeof ApiOgPortalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/dashboard'
    | '/embed-demo'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$view'
    | '/portal/$workspaceSlug'
    | '/api/auth/$'
    | '/api/og/'
    | '/api/og/portal/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/dashboard'
    | '/embed-demo'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$view'
    | '/portal/$workspaceSlug'
    | '/api/auth/$'
    | '/api/og'
    | '/api/og/portal/$slug'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/dashboard'
    | '/embed-demo'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$view'
    | '/portal/$workspaceSlug'
    | '/api/auth/$'
    | '/api/og/'
    | '/api/og/portal/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmbedDemoRoute: typeof EmbedDemoRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  PortalWorkspaceSlugRoute: typeof PortalWorkspaceSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOgIndexRoute: typeof ApiOgIndexRoute
  ApiOgPortalSlugRoute: typeof ApiOgPortalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-demo': {
      id: '/embed-demo'
      path: '/embed-demo'
      fullPath: '/embed-demo'
      preLoaderRoute: typeof EmbedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$workspaceSlug': {
      id: '/portal/$workspaceSlug'
      path: '/portal/$workspaceSlug'
      fullPath: '/portal/$workspaceSlug'
      preLoaderRoute: typeof PortalWorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$view': {
      id: '/dashboard/$view'
      path: '/$view'
      fullPath: '/dashboard/$view'
      preLoaderRoute: typeof DashboardViewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/og/': {
      id: '/api/og/'
      path: '/api/og'
      fullPath: '/api/og/'
      preLoaderRoute: typeof ApiOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/portal/$slug': {
      id: '/api/og/portal/$slug'
      path: '/api/og/portal/$slug'
      fullPath: '/api/og/portal/$slug'
      preLoaderRoute: typeof ApiOgPortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardViewRoute: typeof DashboardViewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardViewRoute: DashboardViewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmbedDemoRoute: EmbedDemoRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  PortalWorkspaceSlugRoute: PortalWorkspaceSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOgIndexRoute: ApiOgIndexRoute,
  ApiOgPortalSlugRoute: ApiOgPortalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
