export const productionReporterExpectedSnippets = [
  'runCommand(["bun", "scripts/readiness.ts", "--strict"])',
  'runCommand(["bun", "scripts/agent-ready-built.ts"])',
  'runCommand(["bun", "scripts/agent-ready-status.ts", "--json"])',
  'runCommand(["bun", "scripts/agent-ready-live.ts", "--json"])',
  "parseReadinessSummary",
  "parseBuiltSummary",
  "blockersFrom",
  "Pass strict readiness with production environment values loaded.",
  "Build the web and docs apps, then pass built artifact validation.",
  "Pass the live agent-ready validator against amend.sh and docs.amend.sh.",
  "reportSchemaUrl",
  "readinessStrict",
  "checkedAt",
  "--json-file",
  "writeFile",
] as const;

export const refreshReporterExpectedSnippets = [
  "scripts/agent-ready-production.ts",
  "scripts/agent-ready-sync-audit.ts",
  "agent-ready:audit:check",
  "scripts/agent-ready-live.ts",
  "agent-ready-live-report.json",
  "scripts/agent-ready-completion-audit.ts",
  "scripts/agent-ready-status.ts",
  "agent-ready-status.json",
  "--allow-production-blockers",
  "--json-file",
  "agent-ready-completion-audit-report.json",
  "Validate reports and synced audits",
  "status.exitCode",
  "production.exitCode",
  "refreshed with blockers",
] as const;

export const finalGateExpectedSnippets = [
  "Generate strict production report",
  "scripts/agent-ready-production.ts",
  "Generate standalone live report",
  "scripts/agent-ready-live.ts",
  "agent-ready-live-report.json",
  "Validate live report",
  "scripts/agent-ready-live-report-validate.ts",
  "Run strict completion audit",
  "scripts/agent-ready-completion-audit.ts",
  "Generate no-secret status",
  "scripts/agent-ready-status.ts",
  "agent-ready-status.json",
  "Validate status report",
  "scripts/agent-ready-status-report-validate.ts",
  "Require production report to be green",
  "scripts/agent-ready-production-report-validate.ts",
  "Require live report to be green",
  "Require status report to be green",
  "Require completion audit report to be green",
  "scripts/agent-ready-completion-audit-report-validate.ts",
  "scripts/agent-ready-sync-audit.ts",
  "--require-ok",
  "Agent-ready final gate passed",
  "Agent-ready final gate failed",
] as const;

export const completionAuditorExpectedSnippets = [
  "Agent-ready completion audit",
  "maximum-visibility web robots policy exists",
  "web llms.txt maps web and docs resources",
  "Agent-ready live report JSON Schema",
  "https://docs.amend.sh/schemas/agent-ready-live-report.schema.json",
  "Agent-ready status report JSON Schema",
  "https://docs.amend.sh/schemas/agent-ready-status-report.schema.json",
  "canonical and social metadata are wired",
  "structured data is wired",
  "crawlable public content is verified",
  "isParseableJsonObject",
  "parseJsonObject",
  "is parseable JSON object",
  "production launch handoff uses Amend.sh origins",
  "SITE_URL=https://amend.sh",
  "EMAIL_FROM=Amend <updates@amend.sh>",
  "Require status report to be green",
  "saved production report has passing strict readiness",
  "saved production report has all production env loaded",
  "saved production report has passing live validator",
  "saved production report is complete and blocker-free",
  "allowProductionBlockers",
  "reportSchemaUrl",
  "https://docs.amend.sh/schemas/agent-ready-completion-audit-report.schema.json",
  "--json",
  "--json-file",
  "writeFile",
  "missingOrBlocked",
  "Only external production blockers remain.",
  "process.exitCode = 1",
] as const;

export const syncAuditorExpectedSnippets = [
  "agent-ready-production-report.json",
  "agent-ready-live-report.json",
  "assertStandaloneLiveReportSynced",
  "normalizedLiveReport",
  "stableValue",
  "comparableLiveReport",
  "matches the embedded live report",
  "Latest JSON live check",
  "Latest agent-ready status check",
  "Latest agent-ready live check",
  "live report checkedAt",
  "status report checkedAt",
] as const;
