export const liveValidatorExpectedSnippets = [
  "apex is registered",
  "https://rdap.org/domain/",
  "Register ${apex}.",
  "apex is delegated",
  "DNS resolves",
  "resolveCname",
  "Create A/AAAA or CNAME records",
  "aiCrawlerNames",
  "/robots.txt",
  "/sitemap.xml",
  "<lastmod>",
  "<changefreq>",
  "<priority>",
  "extractSitemapLocs",
  "extractMarkdownLinks",
  "duplicateValues",
  "has sitemap loc entries",
  "has no duplicate sitemap locs",
  "sitemap locs stay on expected origin",
  "checkLlmsLinksAgainstSitemaps",
  "web /llms.txt links stay on web or docs origins",
  "web /llms.txt web links appear in web sitemap",
  "web /llms.txt docs links appear in docs sitemap",
  "docs /llms.txt relative links appear in docs sitemap",
  "/brand",
  "/embed-demo",
  "/portal/amend-labs",
  "/llms.txt",
  "/llms-full.txt",
  "/schemas/agent-ready-production-report.schema.json",
  "/schemas/agent-ready-live-report.schema.json",
  "/schemas/agent-ready-status-report.schema.json",
  "/schemas/agent-ready-completion-audit-report.schema.json",
  "content-type",
  "parseJsonObject",
  "is parseable JSON object",
  "text/plain",
  "application/xml",
  "text/html",
  "stays on expected origin",
  "finalUrl.origin === origin",
  "x-robots-tag allows indexing",
  "x-robots-tag",
  "extractJsonLdTypes",
  "has valid JSON-LD",
  "structuredDataTypes",
  "excludes",
  "Disallow:",
  "agent-ready-policy",
  "aiAccessUserAgents",
  "checkAiUserAgentAccess",
  "allows ${userAgent.name}",
  "/dashboard",
  "/api/chat",
  "/api/search",
  'property="og:url"',
  'name="twitter:card"',
  '"@type":"Organization"',
  '"@type":"SoftwareApplication"',
  '"@type":"WebSite"',
  '"@type":"TechArticle"',
  "noindex, nofollow",
  "Source-linked product updates",
  'href="${docsOrigin}/docs"',
  "/docs/quickstart",
  "/docs/integration",
  "/docs/customer-surfaces",
  "/docs/source-events",
  "/docs/automation",
  "/docs/api-reference",
  "/docs/source-trace",
  "/docs/self-hosting",
  "/docs/production-routing",
  "/docs/launch",
  "--json",
  "jsonOutput",
  "--json-file",
  "writeFile",
  "checkedAt",
  "reportSchemaUrl",
  '"$schema"',
  "origins",
  "blockers",
  "nextGates",
  '"const": "bun run agent-ready:production"',
  '"const": "bun run agent-ready:final-gate"',
] as const;

export const builtValidatorExpectedSnippets = [
  "apps/web/dist/client/robots.txt",
  "apps/web/dist/client/sitemap.xml",
  "apps/web/dist/client/llms.txt",
  "apps/fumadocs/.next/server/app/robots.txt.body",
  "apps/fumadocs/.next/server/app/robots.txt.meta",
  "apps/fumadocs/.next/server/app/sitemap.xml.body",
  "apps/fumadocs/.next/server/app/sitemap.xml.meta",
  "apps/fumadocs/.next/server/app/llms.txt.body",
  "apps/fumadocs/.next/server/app/llms.txt.meta",
  "apps/fumadocs/.next/server/app/llms-full.txt.body",
  "apps/fumadocs/.next/server/app/llms-full.txt.meta",
  "apps/fumadocs/.next/server/app/schemas/agent-ready-production-report.schema.json.body",
  "apps/fumadocs/.next/server/app/schemas/agent-ready-production-report.schema.json.meta",
  "apps/fumadocs/.next/server/app/schemas/agent-ready-live-report.schema.json.body",
  "apps/fumadocs/.next/server/app/schemas/agent-ready-live-report.schema.json.meta",
  "apps/fumadocs/.next/server/app/schemas/agent-ready-status-report.schema.json.body",
  "apps/fumadocs/.next/server/app/schemas/agent-ready-status-report.schema.json.meta",
  "apps/fumadocs/.next/server/app/schemas/agent-ready-completion-audit-report.schema.json.body",
  "apps/fumadocs/.next/server/app/schemas/agent-ready-completion-audit-report.schema.json.meta",
  "https://docs.amend.sh/api/chat",
  "https://docs.amend.sh/api/search",
  "metaHasContentType",
  "isParseableJsonObject",
  "built docs robots has text/plain metadata",
  "built docs sitemap has application/xml metadata",
  "built docs llms resources have text/plain metadata",
  "built docs Markdown mirror has text/markdown metadata",
  "built docs production report schema endpoint exposes JSON Schema",
  "built docs live report schema endpoint exposes JSON Schema",
  "built docs status report schema endpoint exposes JSON Schema",
  "built docs completion audit report schema endpoint exposes JSON Schema",
  '"nextGates"',
  '"const": "bun run agent-ready:production"',
  '"const": "bun run agent-ready:final-gate"',
  "application/schema+json",
  "built web sitemap has unique on-origin locs",
  "built web llms.txt links are unique and on allowed origins",
  "built web llms.txt web links appear in web sitemap",
  "built web llms.txt docs links appear in docs sitemap",
  "built docs sitemap has unique on-origin locs",
  "built docs llms.txt links are unique and represented in docs sitemap",
  "agent-ready-policy",
  "extractMarkdownLinks",
  "hasNoDuplicateValues",
  "locsStayOnOrigin",
  "apps/fumadocs/.next/server/app/index.html",
  "apps/fumadocs/.next/server/app/docs/quickstart.html",
  "apps/fumadocs/.next/server/app/llms.mdx/docs/quickstart/content.md.body",
  "Agent-ready built summary",
  "bun run build",
] as const;
