export const liveReportValidatorExpectedSnippets = [
  "agent-ready-live-report.json",
  "reportSchemaUrl",
  "$.$schema",
  "--require-ok",
  "validateConsistency",
  "must equal the number of passing checks",
  "must equal whether passed equals total",
  "must be true when --require-ok is used",
  "Valid agent-ready live report",
  "Invalid agent-ready live report",
] as const;

export const productionReportValidatorExpectedSnippets = [
  "agent-ready-production-report.json",
  "reportSchemaUrl",
  "$.$schema",
  "--require-ok",
  "$.blockers",
  "$.checkedAt",
  "$.steps",
  "validateLiveReport",
  "validateStatusReport",
  "validateReportConsistency",
  "requirePassingStep",
  "statusReportSchemaUrl",
  "liveReportSchemaUrl",
  "must equal whether every step is ok",
  "requiredNextGates",
  "validateExactStringArray",
  "must contain exactly",
  "built",
  "live",
  "readinessStrict",
  "status",
  "Valid agent-ready production report",
  "Invalid agent-ready production report",
] as const;

export const statusReportValidatorExpectedSnippets = [
  "agent-ready-status.json",
  "reportSchemaUrl",
  "$.$schema",
  "--require-ok",
  "requiredNextGates",
  "validateExactStringArray",
  "must account for total minus passed",
  "must be true when --require-ok is used",
  "must be empty when --require-ok is used",
  "must equal total when --require-ok is used",
  "must not be empty when --require-ok is used",
  "Valid agent-ready status report",
  "Invalid agent-ready status report",
] as const;

export const completionAuditReportValidatorExpectedSnippets = [
  "agent-ready-completion-audit-report.json",
  "reportSchemaUrl",
  "$.$schema",
  "--require-ok",
  "$.completionOk",
  "$.missingOrBlocked",
  "$.summary.failed",
  "validateReportConsistency",
  "productionBlockerCheckNames",
  "must equal the number of failing checks",
  "must equal the number of passing checks",
  "must equal completionOk or allowed production blockers",
  "must be true when --require-ok is used",
  "must be empty when --require-ok is used",
  "Valid agent-ready completion audit report",
  "Invalid agent-ready completion audit report",
] as const;
